### ISSUE TITLE
Transaction sending doubt

### ISSUE THREAD

**Issue by Lucioric2000** [greenaddress/gaexamples#4]
ello. I am trying to implement an API in Python for Greenaddres. After 2 days of paying around with the API in api.greenaddress.it and can not get past the login! (in testnet), I moved to the API in https://github.com/greenaddress/gaexamples, but in this API I have questions. In the vault module there are the functions sign_raw_tx, and send_raw_tx, but the issue is how to get the raw_tx parameter. I have tried getting it by the first value of the dictionary that I got in to the object transaction[‘prevout_rawtxs’], having taken the transaction variable by the following statement:
transaction=sender_conn.call('vault.prepare_tx','2000',receiver_receiving_id,'1000',priv_data)
but when I call the function
sigto=sender_conn.call('vault.send_raw_tx',next(iter(transaction["prevoutputs"].values())),{"method":"email","code":otp})      [where otp is the value of the otp requested by the function sender_conn.call("twofactor.request_email",'send_raw_tx')]

There appears an error:
Traceback (most recent call last):
  File "manage.py", line 16, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/predications_django/lib64/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/srv/predications_django/lib64/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/predications_django/lib64/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/predications_django/lib64/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/srv/predications_django/btcliveprice/management/commands/transaction.py", line 47, in handle
    sigto=sender_conn.call('vault.send_raw_tx',sigt['tx'],{"method":"email","code":otp})
  File "/srv/predications_django/gaexamples/gacommon/utils.py", line 51, in call
    return self.wamp.session.call(u'com.greenaddress.' + unicode(name), *args)
  File "/srv/predications_django/lib64/python3.6/site-packages/crochet/_eventloop.py", line 510, in wrapper
    return eventual_result.wait(timeout)
  File "/srv/predications_django/lib64/python3.6/site-packages/crochet/_eventloop.py", line 241, in wait
    result.raiseException()
  File "/srv/predications_django/lib64/python3.6/site-packages/twisted/python/failure.py", line 385, in raiseException
    raise self.value.with_traceback(self.tb)
autobahn.wamp.exception.ApplicationError: ApplicationError(error=<com.greenaddress.error>, args=['http://greenaddressit.com/error#internal', 'Missing prevout: d1eab7d08a4444a6db9de47d583739935820e940234d42d940da5750856daee3:1 (not found)', {}], kwargs={}, enc_algo=None)
So I want to get out how to get correct arguments for the function send_raw_tx (for doing a payment in bitcoins, this time in the testnet network).
Best regards.

**Comment by jgriffiths** [comment]
Hi,

Sorry for the delay in responding. prepare_tx is deprecated, clients need to construct the raw tx themselves and then send it to be signed by the server using send_raw_tx. You can fetch the inputs using txs.get_all_unspent_outputs, get a change address from vault.fund, and add any other arbitrary outputs you wish.

Until our docs and examples are updated, the best way to see this in action is to check the code in GreenBits (java) or GreenAddressWebFiles (JS).
